
version: '3.8'
services:
  db:
    container_name: db
    image: mysql:8.0
    networks:
      - bored-network

    # If you are using mvn and did not create a .env file
    # you can hard code the valuse or just do:
    env_file: .env
    #environment:
    #  - MYSQL_PASSWORD=password
    #  - MYSQL_DATABASE=data_base
    #  - MYSQL_ROOT_PASSWORD=password
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"

  news_posts_app:
    build:
      context: .
    container_name: hacker-news-container
    image: yamtaldev/hacker-news:latest
    ports:
      - "8080:8080"
    networks:
      - bored-network
    depends_on:
      - db

    # If you are using mvn and did not create a .env file
    # you can hard code the valuse or just do:
    env_file: .env
    #environment:
    #  - MYSQL_HOST=data_base_name
    #  - MYSQL_PASSWORD=password
    #  - MYSQL_ROOT_PASSWORD=password
    #  - MYSQL_DATABASE=data_base
    #  - MYSQL_PORT=3306

networks:
  bored-network:
    name: bored-network

volumes:
  dbvol: