###############################################################################
#
# MIT License
#
# Copyright (c) 2023 Tal Aharon
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

###############################################################################

spring:
  config:
    import: env.properties

  datasource:
    # Please fill in your password, username, local MySQL data base url fields
    url: ${DB_DATABASE_URL}
    # Passwrd should be - password: 'your-password'
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    hikari:
          data-source-properties:
            serverTimezone: Asia/Jerusalem

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    # For debugging purposes you can reveal this line
    #show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never
  cache:
    # My nickname
    cache-names: ${CACHE_NAME}
    caffeine:
    # 600 entities to cache is chosen because in the Hacker News web site the 
    # maximun number of posts that are loaded if scrolling down to the end is is 583
    # 30 min caching refresh rate seems resonable for me, caffein was chosen as 
    # a cache mechanism because it is easy to integrate, quick to implement and efficient.
      spec: maximumSize=600, expireAfterAccess=30m
app:
  # This parameter is a configuration for the top post request.
  # 30 Enitites per result from data base.
  top-posts-page-size: 30
