spring:
  datasource:
    url: jdbc:mysql://localhost:3306/akamai?useSSL=false&serverTimezone=UTC
    password: '!Tal@2410'
    username: anato
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never
